### ISSUE TITLE
关于数据集读取的问题

### ISSUE THREAD

**Issue by Gatsby23** [tiger20/LOAM-multi-thread#3]
您好，我发现您在main函数中读取数据集的时候，数据集的格式是pcd格式。但我发现LOAM官方的nsh_indoor并不是这个格式，想问下，这个是您用rosbag转的吗？若想用您的代码跑Kitti的数据集，是不是也需要将bin格式转成pcd格式？

**Comment by bryantaoli** [comment]
> 您好，我发现您在main函数中读取数据集的时候，数据集的格式是pcd格式。但我发现LOAM官方的nsh_indoor并不是这个格式，想问下，这个是您用rosbag转的吗？若想用您的代码跑Kitti的数据集，是不是也需要将bin格式转成pcd格式？

你解决了吗？

**Comment by tiger20** [comment]
> > 您好，我发现您在main函数中读取数据集的时候，数据集的格式是pcd格式。但我发现LOAM官方的nsh_indoor并不是这个格式，想问下，这个是您用rosbag转的吗？若想用您的代码跑Kitti的数据集，是不是也需要将bin格式转成pcd格式？
> 
> 你解决了吗？

需要自己转一下，根据pcl的接口存成pcd文件

**Comment by Gatsby23** [comment]
> > > 您好，我发现您在main函数中读取数据集的时候，数据集的格式是pcd格式。但我发现LOAM官方的nsh_indoor并不是这个格式，想问下，这个是您用rosbag转的吗？若想用您的代码跑Kitti的数据集，是不是也需要将bin格式转成pcd格式？
> > 
> > 
> > 你解决了吗？
> 
> 需要自己转一下，根据pcl的接口存成pcd文件

OK, Thank you very much!
